;this file for FamiTone2 library generated by text2data tool

ninnin_ingame__music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env10
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env8,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env2,@env0,@env11
	.byte $00
	.byte $70 ;instrument $09
	.word @env3,@env0,@env11
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $cc,$cb,$ca,$02,$c9,$02,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env3:
	.byte $c4,$02,$c3,$0c,$c2,$0b,$c1,$12,$c0,$00,$08
@env4:
	.byte $ca,$00,$00
@env5:
	.byte $c9,$c7,$c5,$c4,$c2,$c0,$00,$05
@env6:
	.byte $c7,$c2,$c0,$00,$02
@env7:
	.byte $cd,$cb,$c9,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env8:
	.byte $cc,$c0,$00,$01
@env9:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env10:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02
@env11:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02


@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $84,$41,$01,$33,$33,$33,$01,$3d,$01,$33,$01,$33,$33,$3b,$01,$33
	.byte $01,$33,$01,$36,$85,$32,$85,$3a,$85
@ref1:
	.byte $41,$01,$33,$33,$33,$01,$3d,$01,$33,$01,$33,$33,$01,$8e,$41,$3d
	.byte $3b,$33,$37,$3b,$40,$85,$3d,$3b,$32,$81
@ref2:
	.byte $00,$85,$36,$a5,$36,$85,$32,$a5
@ref3:
	.byte $87,$36,$a5,$36,$85,$3a,$a5
	.byte $ff,$18
	.word @ref0
	.byte $ff,$19
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$07
	.word @ref3
@ref8:
	.byte $00,$85,$40,$8d,$40,$85,$3a,$85,$32,$85,$36,$8d,$32,$85,$36,$85
	.byte $32,$85,$01,$3d,$3b,$3d,$3b,$32,$8d,$36,$81
@ref9:
	.byte $82,$40,$8d,$40,$85,$3a,$85,$32,$85,$36,$8d,$32,$85,$36,$85,$32
	.byte $8d,$3a,$a5
@ref10:
	.byte $40,$8d,$40,$85,$3a,$85,$32,$85,$36,$8d,$32,$85,$36,$85,$32,$85
	.byte $3a,$85,$32,$9d,$32,$85
@ref11:
	.byte $40,$8d,$40,$85,$3a,$85,$32,$85,$36,$8d,$32,$85,$36,$85,$32,$8d
	.byte $3a,$a5
	.byte $ff,$16
	.word @ref10
@ref13:
	.byte $36,$95,$3a,$95,$32,$8d,$36,$95,$3a,$8d,$3c,$95
@ref14:
	.byte $3a,$89,$3c,$89,$3a,$8d,$3b,$37,$3a,$85,$32,$85,$36,$89,$3a,$89
	.byte $3c,$95,$3a,$8d
	.byte $ff,$0c
	.word @ref13
@ref16:
	.byte $01,$8e,$40,$85,$3d,$3b,$3d,$3b,$3c,$85,$3a,$85,$3b,$33,$33,$3b
	.byte $36,$85,$3d,$3b,$3c,$85,$3b,$33,$36,$89,$82,$37,$37,$32,$8d
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref17:
	.byte $8c,$40,$85,$3d,$3b,$3d,$3b,$3c,$85,$3a,$85,$3b,$33,$33,$3b,$36
	.byte $85,$3d,$3b,$3c,$85,$3b,$33,$36,$85
@ref18:
	.byte $40,$85,$3d,$3b,$3d,$3b,$3c,$85,$3a,$85,$3b,$33,$41,$3d,$3b,$33
	.byte $37,$3b,$40,$85,$3d,$3b,$32,$85
@ref19:
	.byte $36,$a5,$36,$85,$32,$ad
@ref20:
	.byte $36,$a5,$36,$85,$3a,$ad
@ref21:
	.byte $40,$85,$3d,$3b,$3d,$3b,$3c,$85,$3a,$85,$3b,$33,$33,$3b,$36,$85
	.byte $3d,$3b,$3c,$85,$3b,$33,$36,$85
	.byte $ff,$18
	.word @ref18
	.byte $ff,$06
	.word @ref19
	.byte $ff,$06
	.word @ref20
@ref25:
	.byte $40,$8d,$40,$85,$3a,$85,$32,$85,$36,$8d,$32,$85,$36,$85,$32,$8d
	.byte $55,$53,$55,$53,$4a,$8d,$4e,$85
	.byte $ff,$12
	.word @ref11
@ref27:
	.byte $58,$8d,$58,$85,$52,$85,$4a,$85,$4e,$8d,$4a,$85,$4e,$85,$4a,$85
	.byte $52,$85,$4a,$9d,$32,$85
	.byte $ff,$12
	.word @ref11
	.byte $ff,$16
	.word @ref27
@ref30:
	.byte $36,$89,$36,$89,$32,$a5,$33,$36,$85,$33,$36,$85,$3a,$8d,$37,$37
	.byte $32,$85,$36,$85
@ref31:
	.byte $3a,$89,$3c,$89,$3a,$8d,$3b,$37,$3a,$85,$32,$85,$4e,$89,$52,$89
	.byte $54,$95,$52,$8d
	.byte $ff,$14
	.word @ref30
@ref33:
	.byte $40,$85,$3d,$3b,$3d,$3b,$3c,$85,$3a,$85,$3b,$33,$33,$3b,$36,$85
	.byte $3d,$3b,$3c,$85,$3b,$33,$36,$8d,$4f,$4f,$4a,$8d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref34:
	.byte $80,$33,$01,$4b,$01,$4b,$49,$33,$01,$59,$01,$59,$3d,$33,$01,$4b
	.byte $01,$4b,$01,$33,$01,$59,$01,$45,$00,$81
@ref35:
	.byte $33,$01,$59,$01,$59,$4b,$33,$01,$59,$01,$59,$01,$33,$01,$59,$01
	.byte $4b,$01,$59,$01,$55,$53,$55,$52,$81
@ref36:
	.byte $33,$01,$4b,$01,$4b,$49,$33,$01,$59,$01,$59,$3d,$33,$01,$4b,$01
	.byte $4b,$01,$33,$01,$59,$01,$45,$00,$81
	.byte $ff,$19
	.word @ref36
	.byte $ff,$19
	.word @ref36
	.byte $ff,$19
	.word @ref35
	.byte $ff,$19
	.word @ref36
	.byte $ff,$19
	.word @ref36
@ref42:
	.byte $32,$95,$3a,$85,$32,$85,$36,$8d,$59,$01,$4b,$01,$59,$00,$89,$55
	.byte $53,$55,$53,$4a,$8d,$4e,$85
@ref43:
	.byte $32,$85,$32,$85,$4a,$85,$32,$85,$32,$85,$4a,$85,$32,$85,$4b,$33
	.byte $36,$85,$36,$85,$4e,$85,$36,$85,$36,$85,$4e,$85,$36,$85,$4f,$36
	.byte $81
@ref44:
	.byte $3a,$85,$3a,$85,$52,$85,$3a,$85,$3a,$85,$52,$85,$3a,$85,$53,$3b
	.byte $3c,$85,$3c,$85,$54,$85,$3c,$85,$3c,$85,$54,$85,$3c,$85,$55,$3c
	.byte $81
	.byte $ff,$21
	.word @ref43
	.byte $ff,$21
	.word @ref44
@ref47:
	.byte $33,$33,$4b,$33,$33,$4b,$33,$4b,$33,$33,$4b,$33,$33,$4b,$33,$4b
	.byte $37,$37,$4f,$37,$37,$4f,$37,$4f,$37,$37,$4f,$37,$37,$4f,$37,$4e
	.byte $81
@ref48:
	.byte $3b,$3b,$53,$3b,$3b,$53,$3b,$53,$3b,$3b,$53,$3b,$3b,$53,$3b,$53
	.byte $3d,$3d,$55,$3d,$3d,$55,$3d,$55,$3d,$3d,$55,$3d,$3d,$55,$3d,$54
	.byte $81
	.byte $ff,$21
	.word @ref47
@ref50:
	.byte $3a,$bd,$3d,$3d,$55,$3d,$3d,$55,$3d,$55,$3d,$3d,$4f,$4b,$4a,$8d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref51:
	.byte $df
@ref52:
	.byte $df
@ref53:
	.byte $df
@ref54:
	.byte $df
@ref55:
	.byte $df
@ref56:
	.byte $df
@ref57:
	.byte $df
@ref58:
	.byte $df
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f9,$85
@ref66:
	.byte $f9,$85
@ref67:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref68:
	.byte $df
@ref69:
	.byte $df
@ref70:
	.byte $df
@ref71:
	.byte $df
@ref72:
	.byte $df
@ref73:
	.byte $df
@ref74:
	.byte $df
@ref75:
	.byte $df
@ref76:
	.byte $f9,$85
@ref77:
	.byte $f9,$85
@ref78:
	.byte $f9,$85
@ref79:
	.byte $f9,$85
@ref80:
	.byte $f9,$85
@ref81:
	.byte $f9,$85
@ref82:
	.byte $f9,$85
@ref83:
	.byte $f9,$85
@ref84:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref85:
	.byte $00
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref86:
	.byte $00
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref87:
	.byte $00
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref88:
	.byte $00
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref89:
	.byte $81
	.byte $fd
	.word @song1ch4loop
