// CHR-ROM Map & decos indexes
// Generated by rle44mapchrrom.exe v0.2 20180625
// Copyleft 2017, 2018 by The Mojon Twins

// Map # 0 read from level0.map (10x2)

// Definitions

#define MAP_00_CHRROM    2
#define MAP_00_BASE      0x0000
#define MAP_00_W         10
#define MAP_00_H         2
#define MAP_00_MAXPANTS  20
#define MAP_00_N_LOCKS   0

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x002F, 
	MAP_00_BASE + 0x005B, MAP_00_BASE + 0x009C, 
	MAP_00_BASE + 0x00CF, MAP_00_BASE + 0x00EE, 
	MAP_00_BASE + 0x0113, MAP_00_BASE + 0x012E, 
	MAP_00_BASE + 0x0149, MAP_00_BASE + 0x017B, 
	0                   , 0                   , 
	MAP_00_BASE + 0x019A, MAP_00_BASE + 0x01CD, 
	MAP_00_BASE + 0x01ED, MAP_00_BASE + 0x0209, 
	0                   , 0                   , 
	0                   , 0                   
};

// Total screens size in bytes is 567

// Map # 1 read from level1.map (8x3)

// Definitions

#define MAP_01_CHRROM    2
#define MAP_01_BASE      0x0237
#define MAP_01_W         8
#define MAP_01_H         3
#define MAP_01_MAXPANTS  24
#define MAP_01_N_LOCKS   4

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x002D, 
	MAP_01_BASE + 0x0063, MAP_01_BASE + 0x008D, 
	MAP_01_BASE + 0x00B4, 0                   , 
	0                   , 0                   , 
	MAP_01_BASE + 0x00E4, MAP_01_BASE + 0x0115, 
	MAP_01_BASE + 0x0129, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x0172, MAP_01_BASE + 0x018F, 
	MAP_01_BASE + 0x01AE, MAP_01_BASE + 0x01C1, 
	MAP_01_BASE + 0x01F7, MAP_01_BASE + 0x0115, 
	MAP_01_BASE + 0x021A, MAP_01_BASE + 0x023B, 
	MAP_01_BASE + 0x0265, 0                   , 
	0                   , 0                   
};

// Total screens size in bytes is 658

// Locks
// These tiles are locks:  15
const unsigned char map_01_locks [] = {
	0x0f, 0x78, 0x0f, 0x94
};

// Map # 2 read from level2.map (8x3)

// Definitions

#define MAP_02_CHRROM    2
#define MAP_02_BASE      0x04C9
#define MAP_02_W         8
#define MAP_02_H         3
#define MAP_02_MAXPANTS  24
#define MAP_02_N_LOCKS   4

// Screens index

const unsigned int map_02_scr_offsets [] = {
	0                   , 0                   , 
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x002B, 
	MAP_02_BASE + 0x0047, 0                   , 
	0                   , 0                   , 
	MAP_02_BASE + 0x006F, MAP_02_BASE + 0x00B1, 
	MAP_02_BASE + 0x00D1, MAP_02_BASE + 0x0101, 
	MAP_02_BASE + 0x0125, MAP_02_BASE + 0x0144, 
	MAP_02_BASE + 0x015F, MAP_02_BASE + 0x0179, 
	MAP_02_BASE + 0x01BA, MAP_02_BASE + 0x01D3, 
	MAP_02_BASE + 0x01EE, 0                   , 
	MAP_02_BASE + 0x0212, MAP_02_BASE + 0x0251, 
	0                   , 0                   
};

// Total screens size in bytes is 625

// Locks
// These tiles are locks:  15
const unsigned char map_02_locks [] = {
	0x0c, 0x7f, 0x0d, 0x7f
};

// Map # 3 read from level3.map (8x3)

// Definitions

#define MAP_03_CHRROM    2
#define MAP_03_BASE      0x073A
#define MAP_03_W         8
#define MAP_03_H         3
#define MAP_03_MAXPANTS  24
#define MAP_03_N_LOCKS   4

// Screens index

const unsigned int map_03_scr_offsets [] = {
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0030, 
	MAP_03_BASE + 0x004E, MAP_03_BASE + 0x0089, 
	MAP_03_BASE + 0x0098, MAP_03_BASE + 0x00BF, 
	MAP_03_BASE + 0x00EF, MAP_03_BASE + 0x0124, 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0152, 
	MAP_03_BASE + 0x004E, MAP_03_BASE + 0x0178, 
	MAP_03_BASE + 0x01B1, MAP_03_BASE + 0x020A, 
	MAP_03_BASE + 0x024B, MAP_03_BASE + 0x0283, 
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , 0                   
};

// Total screens size in bytes is 680

// Locks
// These tiles are locks:  15
const unsigned char map_03_locks [] = {
	0x0b, 0x52, 0x0b, 0x76
};

// Map # 4 read from level4.map (12x1)

// Definitions

#define MAP_04_CHRROM    2
#define MAP_04_BASE      0x09E2
#define MAP_04_W         12
#define MAP_04_H         1
#define MAP_04_MAXPANTS  12
#define MAP_04_N_LOCKS   0

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, MAP_04_BASE + 0x0032, 
	MAP_04_BASE + 0x0058, MAP_04_BASE + 0x007C, 
	MAP_04_BASE + 0x00AA, MAP_04_BASE + 0x00C8, 
	MAP_04_BASE + 0x00EA, MAP_04_BASE + 0x0106, 
	MAP_04_BASE + 0x0132, MAP_04_BASE + 0x016B, 
	MAP_04_BASE + 0x018D, MAP_04_BASE + 0x01B3
};

// Total screens size in bytes is 470

// Map # 5 read from level5.map (12x1)

// Definitions

#define MAP_05_CHRROM    2
#define MAP_05_BASE      0x0BB8
#define MAP_05_W         12
#define MAP_05_H         1
#define MAP_05_MAXPANTS  12
#define MAP_05_N_LOCKS   0

// Screens index

const unsigned int map_05_scr_offsets [] = {
	MAP_05_BASE + 0x0000, MAP_05_BASE + 0x0033, 
	MAP_05_BASE + 0x004D, MAP_05_BASE + 0x0070, 
	MAP_05_BASE + 0x00AA, MAP_05_BASE + 0x00DD, 
	MAP_05_BASE + 0x0121, MAP_05_BASE + 0x0153, 
	MAP_05_BASE + 0x017E, MAP_05_BASE + 0x01A4, 
	MAP_05_BASE + 0x01D3, MAP_05_BASE + 0x0211
};

// Total screens size in bytes is 565

// Map # 6 read from level6.map (4x4)

// Definitions

#define MAP_06_CHRROM    2
#define MAP_06_BASE      0x0DED
#define MAP_06_W         4
#define MAP_06_H         4
#define MAP_06_MAXPANTS  16
#define MAP_06_N_LOCKS   6

// Screens index

const unsigned int map_06_scr_offsets [] = {
	MAP_06_BASE + 0x0000, MAP_06_BASE + 0x0025, 
	0                   , 0                   , 
	MAP_06_BASE + 0x005D, MAP_06_BASE + 0x0083, 
	MAP_06_BASE + 0x00AB, MAP_06_BASE + 0x00D4, 
	MAP_06_BASE + 0x00FD, MAP_06_BASE + 0x0135, 
	MAP_06_BASE + 0x0170, MAP_06_BASE + 0x0187, 
	MAP_06_BASE + 0x01A6, MAP_06_BASE + 0x01D7, 
	MAP_06_BASE + 0x01EB, MAP_06_BASE + 0x0214
};

// Total screens size in bytes is 582

// Locks
// These tiles are locks:  15
const unsigned char map_06_locks [] = {
	0x04, 0x93, 0x08, 0x56, 0x0b, 0x58
};

// Map # 7 read from level7.map (4x6)

// Definitions

#define MAP_07_CHRROM    2
#define MAP_07_BASE      0x1033
#define MAP_07_W         4
#define MAP_07_H         6
#define MAP_07_MAXPANTS  24
#define MAP_07_N_LOCKS   8

// Screens index

const unsigned int map_07_scr_offsets [] = {
	0                   , MAP_07_BASE + 0x0000, 
	0                   , MAP_07_BASE + 0x0000, 
	0                   , MAP_07_BASE + 0x003E, 
	MAP_07_BASE + 0x006C, MAP_07_BASE + 0x0090, 
	MAP_07_BASE + 0x00C6, MAP_07_BASE + 0x00F6, 
	0                   , MAP_07_BASE + 0x011E, 
	0                   , MAP_07_BASE + 0x0157, 
	MAP_07_BASE + 0x0179, MAP_07_BASE + 0x01AA, 
	MAP_07_BASE + 0x01E3, MAP_07_BASE + 0x020C, 
	MAP_07_BASE + 0x0234, MAP_07_BASE + 0x0275, 
	MAP_07_BASE + 0x02AD, MAP_07_BASE + 0x02DD, 
	MAP_07_BASE + 0x030C, MAP_07_BASE + 0x0344
};

// Total screens size in bytes is 878

// Locks
// These tiles are locks:  15
const unsigned char map_07_locks [] = {
	0x09, 0xa0, 0x0e, 0xae, 0x0f, 0xa1, 0x10, 0x5f
};

// Map # 8 read from level8.map (10x2)

// Definitions

#define MAP_08_CHRROM    2
#define MAP_08_BASE      0x13A1
#define MAP_08_W         10
#define MAP_08_H         2
#define MAP_08_MAXPANTS  20
#define MAP_08_N_LOCKS   0

// Screens index

const unsigned int map_08_scr_offsets [] = {
	MAP_08_BASE + 0x0000, MAP_08_BASE + 0x0022, 
	MAP_08_BASE + 0x003D, MAP_08_BASE + 0x0058, 
	MAP_08_BASE + 0x0075, MAP_08_BASE + 0x0097, 
	MAP_08_BASE + 0x00BB, MAP_08_BASE + 0x00DE, 
	MAP_08_BASE + 0x00FA, MAP_08_BASE + 0x011B, 
	MAP_08_BASE + 0x0133, MAP_08_BASE + 0x0159, 
	MAP_08_BASE + 0x017A, MAP_08_BASE + 0x0198, 
	MAP_08_BASE + 0x01B1, MAP_08_BASE + 0x01C8, 
	MAP_08_BASE + 0x01EA, MAP_08_BASE + 0x0205, 
	MAP_08_BASE + 0x022A, MAP_08_BASE + 0x0253
};

// Total screens size in bytes is 647

// Map # 9 read from level9.map (1x10)

// Definitions

#define MAP_09_CHRROM    2
#define MAP_09_BASE      0x1628
#define MAP_09_W         1
#define MAP_09_H         10
#define MAP_09_MAXPANTS  10
#define MAP_09_N_LOCKS   0

// Screens index

const unsigned int map_09_scr_offsets [] = {
	MAP_09_BASE + 0x0000, MAP_09_BASE + 0x0032, 
	MAP_09_BASE + 0x004B, MAP_09_BASE + 0x006B, 
	MAP_09_BASE + 0x0097, MAP_09_BASE + 0x00AE, 
	MAP_09_BASE + 0x00C9, MAP_09_BASE + 0x006B, 
	MAP_09_BASE + 0x00E5, MAP_09_BASE + 0x0107
};

// Total screens size in bytes is 296

// Map # 10 read from levelA.map (2x10)

// Definitions

#define MAP_0A_CHRROM    2
#define MAP_0A_BASE      0x1750
#define MAP_0A_W         2
#define MAP_0A_H         10
#define MAP_0A_MAXPANTS  20
#define MAP_0A_N_LOCKS   0

// Screens index

const unsigned int map_0a_scr_offsets [] = {
	MAP_0A_BASE + 0x0000, 0                   , 
	MAP_0A_BASE + 0x0039, 0                   , 
	MAP_0A_BASE + 0x0072, 0                   , 
	MAP_0A_BASE + 0x00A5, MAP_0A_BASE + 0x00D7, 
	MAP_0A_BASE + 0x010F, 0                   , 
	MAP_0A_BASE + 0x0136, MAP_0A_BASE + 0x0154, 
	0                   , MAP_0A_BASE + 0x0182, 
	MAP_0A_BASE + 0x01B0, MAP_0A_BASE + 0x01CF, 
	MAP_0A_BASE + 0x01F0, MAP_0A_BASE + 0x0224, 
	MAP_0A_BASE + 0x0256, MAP_0A_BASE + 0x0270
};

// Total screens size in bytes is 678

// Map # 11 read from levelB.map (12x2)

// Definitions

#define MAP_0B_CHRROM    2
#define MAP_0B_BASE      0x19F6
#define MAP_0B_W         12
#define MAP_0B_H         2
#define MAP_0B_MAXPANTS  24
#define MAP_0B_N_LOCKS   0

// Screens index

const unsigned int map_0b_scr_offsets [] = {
	MAP_0B_BASE + 0x0000, MAP_0B_BASE + 0x0030, 
	MAP_0B_BASE + 0x0066, MAP_0B_BASE + 0x0066, 
	MAP_0B_BASE + 0x0066, MAP_0B_BASE + 0x0066, 
	MAP_0B_BASE + 0x0072, MAP_0B_BASE + 0x00AB, 
	MAP_0B_BASE + 0x00CF, MAP_0B_BASE + 0x00EB, 
	MAP_0B_BASE + 0x00FC, MAP_0B_BASE + 0x0066, 
	MAP_0B_BASE + 0x010A, MAP_0B_BASE + 0x0130, 
	MAP_0B_BASE + 0x014D, MAP_0B_BASE + 0x016B, 
	MAP_0B_BASE + 0x016B, MAP_0B_BASE + 0x01A5, 
	MAP_0B_BASE + 0x01E1, MAP_0B_BASE + 0x0210, 
	MAP_0B_BASE + 0x0233, MAP_0B_BASE + 0x0258, 
	MAP_0B_BASE + 0x027C, MAP_0B_BASE + 0x029B
};

// Total screens size in bytes is 733

