// ..\dev\assets\enems4.h
// Generated by eneexp3c.exe v0.2 [20190715] (MK1 version)
// Copyleft 2016, 2019 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 0 positions

const unsigned char enems_4_00 [] = {
	0x03, 0x65, 0x97, 0x01, 0
};

const unsigned char enems_4_01 [] = {
	0x03, 0x55, 0x95, 0x02, 0x03, 0x99, 0x59, 0x02, 0
};

const unsigned char enems_4_02 [] = {
	0x27, 0x0f, 0x0e, 0x01, 0
};

const unsigned char enems_4_03 [] = {
	0x27, 0x08, 0x07, 0x01, 0
};

const unsigned char enems_4_04 [] = {
	0x03, 0x36, 0x35, 0x01, 0
};

const unsigned char enems_4_05 [] = {
	0x03, 0x14, 0x75, 0x01, 0
};

const unsigned char enems_4_06 [] = {
	0x02, 0x38, 0x33, 0x01, 0
};

const unsigned char enems_4_07 [] = {
	0x03, 0x46, 0x49, 0x01, 0
};

const unsigned char enems_4_08 [] = {
	0x02, 0x4e, 0x4c, 0x01, 0x01, 0x26, 0x28, 0x01, 0
};

const unsigned char enems_4_09 [] = {
	0x01, 0x38, 0x36, 0x01, 0
};

const unsigned char enems_4_0a [] = {
	0x02, 0x87, 0x89, 0x01, 0x03, 0x06, 0x58, 0x02, 0
};

const unsigned char enems_4_0b [] = {
	0x27, 0x0e, 0x1e, 0x01, 0
};

const unsigned char * const enems_4 [] = {
	enems_4_00, enems_4_01, enems_4_02, enems_4_03, enems_4_04, enems_4_05, enems_4_06, enems_4_07, 
	enems_4_08, enems_4_09, enems_4_0a, enems_4_0b
};

// Bytes: 96 vs. MAP_WxMAP_Hx12 = 144 (66%)

#define KILLABLE_ENEMS_4 12


// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_4 [] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x75, 
	0x00, 0x00, 0x00, 0x00, 0x03, 0x99, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x01, 0x6B, 0x01, 0x6C
};

#define MAX_HOTSPOTS_4_TYPE_0	8
#define MAX_HOTSPOTS_4_TYPE_1	2
#define MAX_HOTSPOTS_4_TYPE_3	2
