// ..\dev\assets\enems9.h
// Generated by eneexp3c.exe v0.2 [20190715] (MK1 version)
// Copyleft 2016, 2019 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 0 positions

const unsigned char enems_9_00 [] = {
	0x01, 0x44, 0x4a, 0x02, 0
};

const unsigned char enems_9_02 [] = {
	0x06, 0x58, 0x59, 0x01, 0x04, 0x8c, 0x84, 0x01, 0
};

const unsigned char enems_9_03 [] = {
	0x04, 0xaa, 0xa4, 0x02, 0
};

const unsigned char enems_9_04 [] = {
	0x04, 0x7b, 0x79, 0x02, 0x04, 0x41, 0x47, 0x02, 0x04, 0x48, 0x78, 0x01};

const unsigned char enems_9_05 [] = {
	0x06, 0x69, 0x68, 0x01, 0
};

const unsigned char enems_9_06 [] = {
	0x02, 0x23, 0x25, 0x01, 0
};

const unsigned char enems_9_07 [] = {
	0x04, 0xa3, 0xaa, 0x01, 0
};

const unsigned char enems_9_08 [] = {
	0x06, 0x36, 0x37, 0x01, 0
};

const unsigned char enems_9_09 [] = {
	0x01, 0x95, 0x91, 0x01, 0
};

const unsigned char * const enems_9 [] = {
	enems_9_00, 0, enems_9_02, enems_9_03, enems_9_04, enems_9_05, enems_9_06, enems_9_07, 
	enems_9_08, enems_9_09
};

// Bytes: 76 vs. MAP_WxMAP_Hx12 = 120 (63%)

#define KILLABLE_ENEMS_9 6


// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_9 [] = {
	0x01, 0x1C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
	0x00, 0x00, 0x00, 0x00};

#define MAX_HOTSPOTS_9_TYPE_0	9
#define MAX_HOTSPOTS_9_TYPE_1	1
