// mscnes.h
// Generated by Mojon Script Compiler MK1 NES
// Copyleft 2013/2014, 2019 The Mojon Twins
 
unsigned char msc_done = 0;
unsigned char msc_cont = 0;
unsigned char msc_x, msc_y, msc_n, msc_m, msc_c;
unsigned char *next_script;
 
void msc_init_all (void) {
    for (gpit = 0; gpit < MAX_FLAGS; gpit ++)
        flags [gpit] = 0;
}
 
unsigned char read_byte (void) {
    return *script++;
}
 
unsigned char read_vbyte (void) {
    msc_c = read_byte ();
    if (msc_c & 128) return flags [msc_c & 127];
    return msc_c;
}
 
void run_script (void) {
    msc_m = 0;
 
    if (script == 0)
        return; 
 
    script_something_done = 0;
 
    while (1) {
        msc_c = read_byte ();
        if (msc_c == 0xFF) break;
        next_script = script + msc_c;
        msc_done = msc_cont = 0;
        while (!msc_done) {
            msc_c = read_byte ();
            switch (msc_c) {
                case 0x30:
                    // IF ALL_ENEMIES_DEAD
                    // Opcode: 30
                    msc_done = (pkilled != BADDIES_COUNT);
                    break;
                case 0xFF:
                    // THEN
                    // Opcode: FF
                    msc_done = 1;
                    msc_cont = 1;
                    script_something_done = 1;
                    break;
            }
        }
        if (msc_cont) {
            msc_done = 0;
            while (!msc_done) {
                msc_c = read_byte ();
                switch (msc_c) {
                    case 0x20:
                        // SET TILE (msc_x, msc_y) = msc_n
                        // Opcode: 20 msc_x msc_y msc_n
                        _x = read_vbyte ();
                        _y = read_vbyte ();
                        _t = read_vbyte ();
                        //clear_update_list ();
                        //update_index = 0;
                        map_set ();
                        break;
                    case 0xFF:
                        msc_done = 1;
                        break;
                }
            }
        }
        script = next_script;
    }
}
